
---
title: USDT and BTC
output:
  html_document: default
  html_notebook: default
  pdf_document: default
  word_document: default
---




```{r install_libraries, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
#install.packages("sqldf")
#install.packages("dummies")
#install.packages("forecast")
#install.packages("orderedLasso")
#install.packages("glmnet")
#install.packages("h2o")
#install.packages("lubridate")
#install.packages("glmnetUtils")
#install.packages("addendum")
#install.packages("testthat")
#devtools::use_testthat

rm(list=ls())

library(sqldf) #for running sql on data frames
library(dummies) #for creating one-hot encoding
library(forecast) #for the Holt-Winters forecast filter
#library(orderedLasso)
library(glmnet) #for running regularized GLM
library(lubridate)
#library(glmnetUtils)
#library(Quandl)
library(scales)
library(quantmod) #extract DJI data
library(imputeTS) #for interpolation of time series
#library(h2o)
library(knitr) #for reproducible research, i.e., Markdown
library(testthat)
#?testthat

```

Select global settings for this analysis.  These include choosing the dependent variable, and offset variable, if any, and the time increment variable (i.e., years, or month/year).


```{r set_globals, message=FALSE, warning=FALSE}

##########################
##Input Global Variables##
##########################

##########################
#Input the column name of the dependent variable to predict.
dependent.variable <- "BTC"
##########################

##########################
#Set the maximum lag for adjusting the variables in the data.
#each variable will get a new column for each lag, up to the maximum set here.
maxlag <- 70
##########################

##########################
#Input the column name that has the time increments in it, such as years, or year/months.
time.increment.variable <- "Date"
##########################

##########################
#Input the end date for the training set
train.end.date <- 2018-12-29
##########################

##########################
#Select whether to include plots with the arima, pre-whitening step
include.arima.plots <- FALSE
##########################

##########################
#Select whether to include quartile to quartile (QQ) plots
include.QQ.plots <- FALSE
##########################

##### dependent variable #####

#Note: this process takes the data in descending order, with the most recent data at the
#bottom, or end of the list/table.

dat <- read.csv("Tether_Market_Cap2.csv")
str(dat)

#write.csv(head(dat, n=100), "dat_head.csv")
#write.csv(head(dat), "sampledata.csv")
#length(dat[,1])

sink("summary.txt")
summary(dat)
sink()

BTC <- Quandl("BITFINEX/BTCUSD", api_key="DJGcfzQc5RYP1JSycMBv")
#BTC.monthly <- Quandl("BITFINEX/BTCUSD", api_key="DJGcfzQc5RYP1JSycMBv", collapse="daily")
BTC.monthly <- Quandl("BITFINEX/BTCUSD", api_key="DJGcfzQc5RYP1JSycMBv")
BTC$Index <- (1:length(BTC[,1]))
#head(BTC)
min_length <- min(c(length(dat[,1]), length(BTC[,1])))
dat <- dat[1:min_length,]
BTC <- BTC[1:min_length,]
#head(BTC)
#tail(BTC)
BTC.rev <- sapply(BTC, rev)
#head(BTC)
#tail(BTC)

SeriesData <- cbind(dat, BTC=BTC.rev[,"Last"])
SeriesData <- SeriesData[,-c(1,2)] #remove index and date columns
#head(SeriesData)
#tail(SeriesData)
write.csv(SeriesData, "SeriesData.csv")

#fix column names to have proper name syntax
tidy.colnames <- make.names(colnames(SeriesData), unique=TRUE)
colnames(SeriesData) <- tidy.colnames

#get list of variables, and paste into exported list below
write.csv(file="colnames.csv",x=tidy.colnames)

#Use the list below as a starting point for selecting predictor variables. Uncomment variables to select.

x.names <- setdiff(colnames(SeriesData), "BTC")
x <- SeriesData[, x.names]
#colnames(SeriesData)

nrows.x <- nrow(x)

nlags <- nrows.x - nrows.y
nrows.lagged.births <- nrows.births - nlags

#function to add time lags to the predictor variables in a new matrix
time_lag_matrix2 <- function (x, maxlag) {
    p = ncol(x)
    N = nrow(x) - maxlag - 1
#    x_new_num_col = maxlag * p + p #as a check
    x_new = NULL
    for (j in 1:p) {
      for (i in 1:(maxlag + 1)) {
        x_temp = x[(i):(N + i), j]
        x_new = cbind(x_new,as.vector(x_temp))
      }
    }
    return(x_new)
}

year <- raw.birth.data$Year
births <- raw.birth.data$Births

birth.data.lagged <- time_lag_matrix2(x=raw.birth.data, maxlag=nlags)
str(birth.data.lagged)
str(dep.close)
write.csv(birth.data.lagged, "birth_data_lagged.csv")

years.lagged <- birth.data.lagged[,1:length(birth.data.lagged[1,])/2]
#year.names <- years.lagged[,1]

begin.birthdata <- length(birth.data.lagged[1,])/2+1
end.birthdata <- length(birth.data.lagged[1,])
births.lagged <- birth.data.lagged[,begin.birthdata:end.birthdata]

write.csv(years.lagged, "years.lagged.csv")

Y <- cbind(births.lagged, dep.close[,dependent.variable])
#str(Y)
#Y.rev <- apply(Y, 2, rev)

#split data into training and test sets: two thirds, and one third respectively
T1=floor(nrow(Y)/4)
T2=floor(3*nrow(Y)/4)

train.data = Y[1:T2,]
forecast.data = Y[(T2+1):(T1+T2),]

y.train <- train.data[,length(Y[1,])]
x.train <- train.data[,1:(length(Y[1,])-1)]

cvfitlm <- cv.glmnet(x=x.train, y=y.train, family="gaussian", alpha=1)
cvfitlm.coef.lambda.1se <- coef(cvfitlm, s = "lambda.1se")
#str(cvfitlm.coef.lambda.1se)

y.forecast <- forecast.data[,length(Y[1,])]
x.forecast <- forecast.data[,1:(length(Y[1,])-1)]



```

#Forecast

```{r}

end.year <- year(end)
pop.ages <- end.year - nrows.lagged.births - year[cvfitlm.coef.lambda.1se@i]
coef.table <- cbind(c("y-intercept", paste("Age: ", pop.ages, sep="")), round(cvfitlm.coef.lambda.1se@x, 5))
colnames(coef.table) <- c("Variable Name", "Coefficient")
kable(coef.table)

```

##Forecast Graph

```{r}

#### build forecast set the maximizes the amount of data that can be used

max.forecast.length <- max(cvfitlm.coef.lambda.1se@i)
#raw.birth.data$Year[30]
end.x.forecast <- nrows.births - max.forecast.length

#pop.ages <- end.year - nrows.lagged.births - year[cvfitlm.coef.lambda.1se@i]

###to do next: create a loop to cycle through each lag...
#raw.birth.data$Births[max.forecast.length:end.x.forecast]

forecast.set <- NULL
year.set <- NULL
tmp <- NULL
tmp2 <- NULL
#j=1
for(j in 2:length(cvfitlm.coef.lambda.1se@i)){
   a <- cvfitlm.coef.lambda.1se@i[j] + nrows.lagged.births - 1
   b <- cvfitlm.coef.lambda.1se@i[j] + nrows.lagged.births + max.forecast.length - 1
   forecast.set <- raw.birth.data$Births[a:b]
   year.set <- raw.birth.data$Year[a:b]
   tmp <- rbind(tmp, forecast.set)
   tmp2 <- rbind(tmp2, year.set)
   forecast.set <- tmp
   year.set <- tmp2
}
str(forecast.set)
write.csv(forecast.set, "forecast_set.csv")
write.csv(year.set, "year_set.csv")
coefs <- cvfitlm.coef.lambda.1se@x

frcst.x.tmp <- coefs[2:length(coefs)] * forecast.set
frcst.x <- apply(frcst.x.tmp, 2, sum) + coefs[1]
write.csv(frcst.x, "frcst_x.csv")

predictions <- predict(cvfitlm, newx=x.train, type="response", s=cvfitlm$lambda.1se)
predict.ahead <- predict(cvfitlm, newx=x.forecast, type="response", s=cvfitlm$lambda.1se)

#str(x.forecast)
pdf("glmnet_forecast.pdf")
plot(c(y.train, predict.ahead), type='p', main = "Forecast", ylab="Values", xlab="Time")
lines(y.train, col = "black", lty = 1, lwd = 2)
lines(c(predictions,predict.ahead), col = "green", lty = 1, lwd = 2)
legend("topleft", c("Forecast", "Actual"), col = c("green", "black"), text.col = "black", lty = c(1, 1, 1, 1, 2), lwd = c(2, 2, 2, 1, 2), merge = TRUE, bg = 'gray90', cex = .75)
dev.off()

pdf("glmnet_forecast2.pdf")
plot(c(y.train, frcst.x), type='p', main = "Forecast", ylab="Values", xlab="Time")
lines(y.train, col = "black", lty = 1, lwd = 2)
lines(c(predictions, frcst.x), col = "green", lty = 1, lwd = 2)
legend("topleft", c("Forecast", "Actual"), col = c("green", "black"), text.col = "black", lty = c(1, 1, 1, 1, 2), lwd = c(2, 2, 2, 1, 2), merge = TRUE, bg = 'gray90', cex = .75)
dev.off()

plot(c(y.train, predict.ahead), type='p', main = "Forecast", ylab="Values", xlab="Time")
lines(y.train, col = "black", lty = 1, lwd = 2)
lines(c(predictions,predict.ahead), col = "green", lty = 1, lwd = 2)
legend("topleft", c("Forecast", "Actual"), col = c("green", "black"), text.col = "black", lty = c(1, 1, 1, 1, 2), lwd = c(2, 2, 2, 1, 2), merge = TRUE, bg = 'gray90', cex = .75)

plot(c(y.train, frcst.x), type='p', main = "Forecast", ylab="Values", xlab="Time")
lines(y.train, col = "black", lty = 1, lwd = 2)
lines(c(predictions, frcst.x), col = "green", lty = 1, lwd = 2)
legend("topleft", c("Forecast", "Actual"), col = c("green", "black"), text.col = "black", lty = c(1, 1, 1, 1, 2), lwd = c(2, 2, 2, 1, 2), merge = TRUE, bg = 'gray90', cex = .75)

```